#!/usr/bin/env bash
# Installs and configures HAproxy on your lb-01 server.

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo sed -i -e "$aENABLED=1\n" /etc/default/haproxy
sudo sed -i -e "$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 347604-web-01 100.26.153.46 check\n\tserver 347604-web-02 18.232.73.156:80 check\n" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
